--- ../Dockerfile	2025-10-23 04:32:39
+++ o11y--course--field--100-otel-k8s--main/_challenges/03-manual/Dockerfile	2025-10-23 07:41:23
@@ -9,7 +9,15 @@
 
 WORKDIR /usr/src/app
 
+ARG EDOT_VERSION=1.5.0
+RUN wget -O edot-javaagent.jar https://repo1.maven.org/maven2/co/elastic/otel/elastic-otel-javaagent/$EDOT_VERSION/elastic-otel-javaagent-$EDOT_VERSION.jar 
+
 COPY --from=build /usr/src/app/target/recorder-0.0.1-SNAPSHOT.jar /usr/src/app/recorder.jar
 
+ENV OTEL_SERVICE_NAME="recorder-java"
+
 EXPOSE 9003
-ENTRYPOINT ["java", "-jar", "/usr/src/app/recorder.jar"]
+ENTRYPOINT ["java", \
+"-javaagent:edot-javaagent.jar", \
+"-Dotel.inferred.spans.enabled=true", "-Dotel.inferred.spans.sampling.interval=1ms", "-Dotel.inferred.spans.min.duration=0ms", "-Dotel.inferred.spans.included.classes=com.example.*", \
+"-jar", "/recorder.jar"]
