---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-claim0
  namespace: $NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: frontend-$SERVICE_VERSION
  namespace: $NAMESPACE
spec:
  template:
    spec:
      tolerations:
      - key: "REGION"
        operator: "Equal"
        value: "$REGION"
        effect: "PreferNoSchedule"
      containers:
        - image: $REPO/frontend:$COURSE
          imagePullPolicy: Always
          name: frontend
          volumeMounts:
            - mountPath: /build
              name: frontend-claim0
      restartPolicy: Never
      volumes:
        - name: frontend-claim0
          persistentVolumeClaim:
            claimName: frontend-claim0
---

